"""Criação de todo o esquema inicial do VYZOR

Revision ID: 63bb286f38ba
Revises: 
Create Date: 2025-09-03 17:20:09.213045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63bb286f38ba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acoes_recomendadas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('prioridade', sa.String(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('categorias_produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('percentual', sa.Numeric(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('departamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('indicadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('valor_numerico', sa.Numeric(), nullable=False),
    sa.Column('unidade', sa.String(length=10), nullable=True),
    sa.Column('prefixo', sa.String(length=10), nullable=True),
    sa.Column('variacao', sa.Numeric(), nullable=True),
    sa.Column('tendencia', sa.String(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(), nullable=False),
    sa.Column('descricao', sa.TEXT(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('metas_receita',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes', sa.String(), nullable=False),
    sa.Column('receita', sa.Numeric(), nullable=True),
    sa.Column('meta', sa.Numeric(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtos_top',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('vendas', sa.Integer(), nullable=True),
    sa.Column('receita', sa.Numeric(), nullable=True),
    sa.Column('crescimento', sa.Numeric(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('regras_validacao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('campo_alvo', sa.String(), nullable=False),
    sa.Column('tipo_validacao', sa.String(), nullable=False),
    sa.Column('parametros', sa.JSON(), nullable=True),
    sa.Column('mensagem_erro', sa.TEXT(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('perfil', sa.String(), nullable=True),
    sa.Column('departamento_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['departamento_id'], ['departamentos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_table('atividades_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('tabela_afetada', sa.String(), nullable=True),
    sa.Column('registro_id', sa.Integer(), nullable=True),
    sa.Column('dados_antes', sa.JSON(), nullable=True),
    sa.Column('dados_depois', sa.JSON(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.TEXT(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('nome_arquivo', sa.String(), nullable=False),
    sa.Column('tipo_arquivo', sa.String(), nullable=False),
    sa.Column('tamanho_bytes', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('total_registros', sa.Integer(), nullable=True),
    sa.Column('registros_validos', sa.Integer(), nullable=True),
    sa.Column('registros_invalidos', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('atualizado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs_importacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('etapa', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('mensagem', sa.TEXT(), nullable=True),
    sa.Column('detalhes', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_importados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('importacao_id', sa.Integer(), nullable=True),
    sa.Column('numero_linha', sa.Integer(), nullable=True),
    sa.Column('dados_originais', sa.JSON(), nullable=True),
    sa.Column('dados_processados', sa.JSON(), nullable=True),
    sa.Column('status_validacao', sa.String(), nullable=True),
    sa.Column('erros', sa.JSON(), nullable=True),
    sa.Column('criado_em', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['importacao_id'], ['importacoes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_importados')
    op.drop_table('logs_importacoes')
    op.drop_table('importacoes')
    op.drop_table('atividades_usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('regras_validacao')
    op.drop_table('produtos_top')
    op.drop_table('metas_receita')
    op.drop_table('insights')
    op.drop_table('indicadores')
    op.drop_table('departamentos')
    op.drop_table('categorias_produtos')
    op.drop_table('acoes_recomendadas')
    # ### end Alembic commands ###
