"""descrição da mudança

Revision ID: 763fc9ad8e11
Revises: e1a2b3c4d5e6
Create Date: 2025-10-19 18:24:35.792126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '763fc9ad8e11'
down_revision: Union[str, Sequence[str], None] = 'e1a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('TesteValor')
    op.drop_index(op.f('ix_saas_financeiros_id_transacao'), table_name='saas_registros_financeiros')
    op.drop_constraint(op.f('saas_registros_financeiros_importacao_id_fkey'), 'saas_registros_financeiros', type_='foreignkey')
    op.create_foreign_key(None, 'saas_registros_financeiros', 'importacoes', ['importacao_id'], ['id'])
    op.drop_index(op.f('ix_saas_operacionais_id_evento'), table_name='saas_registros_operacionais')
    op.drop_constraint(op.f('saas_registros_operacionais_importacao_id_fkey'), 'saas_registros_operacionais', type_='foreignkey')
    op.create_foreign_key(None, 'saas_registros_operacionais', 'importacoes', ['importacao_id'], ['id'])
    op.drop_index(op.f('ix_saas_produtos_id_venda'), table_name='saas_registros_produtos')
    op.drop_index(op.f('ix_saas_produtos_sku_produto'), table_name='saas_registros_produtos')
    op.drop_constraint(op.f('saas_registros_produtos_importacao_id_fkey'), 'saas_registros_produtos', type_='foreignkey')
    op.create_foreign_key(None, 'saas_registros_produtos', 'importacoes', ['importacao_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'saas_registros_produtos', type_='foreignkey')
    op.create_foreign_key(op.f('saas_registros_produtos_importacao_id_fkey'), 'saas_registros_produtos', 'importacoes', ['importacao_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_saas_produtos_sku_produto'), 'saas_registros_produtos', ['sku_produto'], unique=False)
    op.create_index(op.f('ix_saas_produtos_id_venda'), 'saas_registros_produtos', ['id_venda'], unique=False)
    op.drop_constraint(None, 'saas_registros_operacionais', type_='foreignkey')
    op.create_foreign_key(op.f('saas_registros_operacionais_importacao_id_fkey'), 'saas_registros_operacionais', 'importacoes', ['importacao_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_saas_operacionais_id_evento'), 'saas_registros_operacionais', ['id_evento'], unique=True)
    op.drop_constraint(None, 'saas_registros_financeiros', type_='foreignkey')
    op.create_foreign_key(op.f('saas_registros_financeiros_importacao_id_fkey'), 'saas_registros_financeiros', 'importacoes', ['importacao_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_saas_financeiros_id_transacao'), 'saas_registros_financeiros', ['id_transacao'], unique=True)
    op.create_table('TesteValor',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('data_extracao', sa.DATE(), server_default=sa.text('CURRENT_DATE'), autoincrement=False, nullable=False),
    sa.Column('receita_total', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('receita_media_por_pedido', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_pedidos', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('novos_clientes', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('taxa_conversao_percent', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('TesteValor_pkey'))
    )
    # ### end Alembic commands ###
