"""Alterado ip_address de INET para String

Revision ID: 9a79991e19cd
Revises: c8944d0e2ae1
Create Date: 2025-09-05 08:50:06.453732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9a79991e19cd'
down_revision: Union[str, Sequence[str], None] = 'c8944d0e2ae1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atividades_usuarios', 'ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('atividades_usuarios', 'ip_address',
               existing_type=sa.String(),
               type_=postgresql.INET(),
               existing_nullable=True)
    # ### end Alembic commands ###
