# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy to Production

on:
  push:
    branches:
      - main  # GATILHO: Roda na branch 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # OTIMIZAÇÃO: Usando versão estável

      # CORREÇÃO: Voltando a fazer o upload do diretório inteiro, como no original que funcionava.
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app-prod
          path: |
            .
            !venv/

  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to Production App Service
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app-prod
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_8437B76B53F5499AA0833AADB271CA97 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_04091F143131437BB7CFF6ED0F6D3FC8 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_3085E005A7D04623AFEB20DE110976E5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'vyzor-backend-prod'

          

